trigger:
- master  # Adjust this to your default branch name, e.g., 'master' or 'main'

pool:
  vmImage: 'ubuntu-latest'  # Microsoft-hosted agent

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'  # Specify the Python version you want
    addToPath: true

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    python -m unittest discover
  displayName: 'Run tests'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'MyAzureServiceConnection'  # The name of your Azure service connection
    appName: 'webappusecase5'  # Name of your Azure Web App
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'  # Path to your deployment package
    deploymentMethod: 'zipDeploy'
  displayName: 'Deploy to Azure Web App'
